### ISSUE TITLE
Silverlight.jss issue

### ISSUE THREAD

**Issue by Thomgi** [autopkg/jss-recipes#50]
Hi there,

Since few days, I'm encoutered an issue with Silverlight through autopkg/autopkgr.

Here's what I can give you :
My recipe override :
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Identifier</key>
	<string>local.jss.Silverlight</string>
	<key>Input</key>
	<dict>
		<key>CATEGORY</key>
		<string>Plugin_Internet</string>
		<key>DESCRIPTION</key>
		<string></string>
		<key>DOWNLOAD_URL</key>
		<string>http://www.microsoft.com/getsilverlight/handlers/getsilverlight.ashx</string>
		<key>GROUP_NAME</key>
		<string>%NAME%-update-smart</string>
		<key>GROUP_TEMPLATE</key>
		<string>%RECIPE_DIR%/SilverlightSmartGroupTemplate.xml</string>
		<key>ICON</key>
		<string>%RECIPE_DIR%/Silverlight.png</string>
		<key>NAME</key>
		<string>Silverlight</string>
		<key>POLICY_CATEGORY</key>
		<string>Plugin_Internet</string>
		<key>POLICY_TEMPLATE</key>
		<string>%RECIPE_DIR%/PolicyTemplate.xml</string>
		<key>USER_AGENT</key>
		<string>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.28.10 (KHTML, like Gecko) Version/6.0.3 Safari/536.28.10</string>
		<key>JSS_SUPPRESS_WARNINGS</key>
		<string>true</string>
	</dict>
	<key>ParentRecipe</key>
	<string>com.github.autopkg.jss.Silverlight</string>
</dict>
</plist>
```

When I run Silverlight.pkg (which is parent off Silverlight.jss - com.github.autopkg.pkg.Silverlight), it works fine, but when I run Silverlight.jss both from autopkgr and using command line autopkg, I get the following error :
```
admin$ autopkg run Silverlight.jss -vvvvv
Processing Silverlight.jss...
Failed.
Receipt written to /tmp/receipts/Silverlight-receipt-20160128-095208.plist

The following recipes failed:
    Silverlight.jss
        JSSImporter requires missing argument version

Nothing downloaded, packaged or imported.
```

```
Traceback (most recent call last): File "/usr/local/bin/autopkg", line 1460, in run_recipes autopackager.verify(recipe) File "/Library/AutoPkg/autopkglib/__init__.py", line 417, in verify % (step["Processor"], key)) AutoPackagerError: JSSImporter requires missing argument version
```

Can you help me (again :) ) on this ?

**Comment by Thomgi** [comment]
I also try this command :
```
autopkg run Silverlight.jss -p /Users/admin/Library/AutoPkg/Cache/com.github.autopkg.pkg.Silverlight/Silverlight-5.1.41212.0.pkg
```
to use pkg downloaded by Silverlight.jss recipe, with the same error message.

**Comment by sheagcraig** [comment]
The autopkg environment doesn't have a variable named "version". This is usually the result of using the PlistReader processor, which dynamically adds output variables, rather than commits to having a guaranteed output variable of version. Then the AutoPkg preprocessing happens and sees that something requires `version` (JSSImporter) and it has to stop.

Even though it sounds crazy, the solution is to put an input variable into your recipe that is just:
```
<key>version</key>
<string></string>
```
That's enough to satisfy AutoPkg, and the version will get set appropriately along the way.
